language: python
python:
  - "2.7"

sudo: 
  false

addons:
  apt:
    packages:
    - language-pack-en
    - language-pack-de

install:
  pip install coveralls

script: 
  nosetests --with-coverage --cover-package=rates

after_success:
  coveralls
