language: python
python:
  - "2.7"

sudo: 
  true

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de

install:
  pip install coveralls

script: 
  nosetests --with-coverage --cover-package=rates

after_success:
  coveralls